In [9]:
import pandas as pd
gpt_labels = pd.read_csv("../raw/indian_dialect/answer-chatgpt", sep="\t", header=None)
human_labels = pd.read_csv("../raw/indian_dialect/indian_english_dialect.csv")
gpt_labels

       0                           1  2
0      0   Resumptive Object Pronoun  M
1      1             Copula Omission  N
2      2   Mass Nouns As Count Nouns  N
3      3           None of the Above  L
4      4           None of the Above  K
..   ...                         ... ..
261  261           Lack Of Agreement  K
262  262        Preposition Omission  M
263  263           None of the Above  R
264  264           None of the Above  M
265  265  Resumptive Subject Pronoun  V

[266 rows x 3 columns]

In [10]:
human_labels

,Example,Feature
0,two years I stayed alone,Preposition Omission
1,at the Tirupati temple I stayed one or two days,None of the Above
2,person I like most is from the mechanical depa...,Article Omission
3,there are five balls,None of the Above
4,I like the cake very much.,None of the Above
...,...,...
261,i don’t have to make so much adjustment,None of the Above
262,corruption is there obviously,"Non-initial Existential ""is / are there"""
263,"anybody giving donation, we are giving receipt",Habitual Progressive
264,my father works for a mining company,None of the Above
265,"the children are playing outside, aren’t they?",None of the Above

In [15]:
to_label = {}
for i, label in enumerate(human_labels["Feature"].unique()):
    to_label[label] = i
to_label

{'Preposition Omission': 0,
 'None of the Above': 1,
 'Article Omission': 2,
 'Non-initial Existential "is / are there"': 3,
 'General Extender "and all"': 4,
 'Focus Only': 5,
 'Left Dislocation': 6,
 'Resumptive Object Pronoun': 7,
 'Resumptive Subject Pronoun': 8,
 'Mass Nouns As Count Nouns': 9,
 'Lack Of Agreement': 10,
 'Topicalized Non-argument Constituent': 11,
 'Invariant Tag "isn’t it, no, na"': 12,
 'Stative Progressive': 13,
 'Object Fronting': 14,
 'Direct Object Pronoun Drop': 15,
 'Prepositional Phrase Fronting With Reduction': 16,
 'Habitual Progressive': 17,
 'Lack Of Inversion In Wh-questions': 18,
 'Extraneous Article': 19,
 'Focus Itself': 20,
 'Inversion In Embedded Clause': 21,
 'Copula Omission': 22}

In [12]:
import numpy as np
accuracy = np.sum(gpt_labels[1] == human_labels["Feature"]) / len(gpt_labels)
accuracy

0.21052631578947367

In [18]:
gpt_labels["label"] = gpt_labels[1].map(to_label)
human_labels["label"] = human_labels["Feature"].map(to_label)
data = pd.DataFrame({
    "sentence": human_labels["Example"],
    "gold_label": human_labels["label"],
    "gpt_label": gpt_labels["label"],
    "gold_label_text": human_labels["Feature"]
})

data.to_csv("data.csv")

data

,sentence,gold_label,gpt_label,gold_label_text
0,two years I stayed alone,0,7,Preposition Omission
1,at the Tirupati temple I stayed one or two days,1,22,None of the Above
2,person I like most is from the mechanical depa...,2,9,Article Omission
3,there are five balls,1,1,None of the Above
4,I like the cake very much.,1,1,None of the Above
...,...,...,...,...
261,i don’t have to make so much adjustment,1,10,None of the Above
262,corruption is there obviously,3,0,"Non-initial Existential ""is / are there"""
263,"anybody giving donation, we are giving receipt",17,1,Habitual Progressive
264,my father works for a mining company,1,1,None of the Above
265,"the children are playing outside, aren’t they?",1,8,None of the Above

In [22]:
for i in range(0, 23):
    print(len(data[data["gold_label"] == i]) == len(data[data["gpt_label"] == i]), i)

True 0
True 1
True 2
True 3
True 4
True 5
True 6
True 7
True 8
True 9
True 10
True 11
True 12
True 13
True 14
True 15
True 16
True 17
True 18
True 19
True 20
True 21
True 22